### ISSUE TITLE
Puma 5.0.1 undefined method `min_threads='

### ISSUE THREAD

**Issue by janklimo** [testdouble/cypress-rails#46]
Using Puma 5.0.1 the test runner crashes before it spins up the server. This is because `min/max_threads` used to be accessors but now they're [readers](https://github.com/puma/puma/blob/3212427f1e6fddb467d37624e7df8aa28820f862/lib/puma/server.rb#L37). Introduced in [this commit](https://github.com/puma/puma/commit/bbbdfb8f4c9ac1da5140d910cd0814bd7478791a).

Should we remove this line and use Puma's [defaults](https://github.com/puma/puma/blob/3212427f1e6fddb467d37624e7df8aa28820f862/lib/puma/server.rb#L82-L83) instead?

https://github.com/testdouble/cypress-rails/blob/41e5fe2ae90dacee38263a72ca4d3e8378d558d8/lib/cypress-rails/server/puma.rb#L25

**Comment by searls** [comment]
This change was reverted in 5.0.2 by @nateberkopec, released two hours ago. Tests for the gem are passing for me under the latest 5.0.2

**Comment by janklimo** [comment]
Confirmed that this works with 5.0.2

**Comment by nateberkopec** [comment]
Sorry for the trouble, folks! 🙇
